"""The product's console layer: recorded in this repository, applied onto upstream.

The console is built from CowAgent 2.1.9 (`tools/upstream/cowagent` upstream
release), and a fresh machine gets that tree from the release archive. What
upstream does not have is the product: the chat page under the Oneiro name, the
settings page that talks to `/oneiro/api/settings`, the sidebar entry for the
graph panel, the MCP page, the Russian strings, and the server routes they call.

Before this file existed, all of that lived only inside the vendor tree - a
directory the workspace deliberately keeps out of git - so a fresh clone, and
therefore any publish, would have delivered a product without its own front
door, and reinstalling upstream would have erased it. This is the answer: the
product's console files are stored here, and `apply` puts them onto the vendor
tree with drift detection instead of blind copying.

Two subcommands:

    python console/overlay.py build --pristine DIR --vendor DIR
        Regenerate `console/overlay/` and `console/manifest.json` from a
        pristine upstream tree and the vendor tree the product currently runs
        from. Run after editing any console file, so the repository keeps
        matching what the product actually is.

    python console/overlay.py apply --vendor DIR [--dry-run]
        Put the recorded files onto a vendor tree. Every file is checked
        against three states and only one of them is overwritten:

          already the product's version  -> left alone (idempotent)
          still the pristine upstream    -> replaced
          anything else                  -> refused, with the sha256 printed

        The refusal is the point. A silent overwrite of a file that someone
        else has since edited is how work disappears; saying so costs nothing.

What is deliberately not recorded: `desktop/` (a separate Electron surface with
its own build output, not part of the web product), vendor data
(`config.json`, plugin configs), logs and caches. `manifest.json` names the
release it was built against, so a mismatch is visible rather than assumed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent
OVERLAY = HERE / "overlay"
MANIFEST = HERE / "manifest.json"

UPSTREAM = {"name": "cowagent", "release": "2.1.9"}

# Directories that are not the product: build output, caches, virtualenvs, and
# the Electron desktop surface (its own product, shipped from its own build).
SKIP_DIRS = {".venv", "__pycache__", ".git", "node_modules", "desktop", "_tmp", ".pytest_cache",
             # Plugin enablement and per-install data, not product source.
             "plugins"}
SKIP_SUFFIX = {".log", ".pyc", ".pyo"}
SKIP_PREFIX = ("run-",)
# Conversation and credential files: one machine's state, and the wrong class of
# file to put in a repository at all.
SKIP_NAMES = {"config.json", ".env"}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def wanted(rel: Path) -> bool:
    if any(part in SKIP_DIRS for part in rel.parts):
        return False
    if rel.suffix in SKIP_SUFFIX or rel.name in SKIP_NAMES:
        return False
    return not rel.name.startswith(SKIP_PREFIX)


def walk(root: Path):
    for path in sorted(root.rglob("*")):
        if path.is_file():
            rel = path.relative_to(root)
            if wanted(rel):
                yield rel


def build(pristine: Path, vendor: Path) -> int:
    if not pristine.is_dir() or not vendor.is_dir():
        print("нужны оба дерева: --pristine и --vendor", file=sys.stderr)
        return 2
    if OVERLAY.exists():
        shutil.rmtree(OVERLAY)
    files = []
    for rel in walk(vendor):
        target = vendor / rel
        source = pristine / rel
        if source.exists() and source.read_bytes() == target.read_bytes():
            continue                     # upstream file, untouched by the product
        rel_posix = rel.as_posix()
        entry = {
            "path": rel_posix,
            "kind": "changed" if source.exists() else "new",
            "pristine_sha256": sha256(source) if source.exists() else None,
            "product_sha256": sha256(target),
        }
        files.append(entry)
        destination = OVERLAY / rel
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(target, destination)

    stale = [rel for rel in walk(OVERLAY) if not (vendor / rel).exists()]
    manifest = {
        "upstream": UPSTREAM,
        "note": "generated by console/overlay.py build; do not hand-edit",
        "files": files,
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8")
    changed = sum(1 for f in files if f["kind"] == "changed")
    added = len(files) - changed
    print(f"Записано в репозиторий: {len(files)} файлов "
          f"({changed} изменённых, {added} новых), {sum((OVERLAY / f['path']).stat().st_size for f in files)/1024:.0f} КБ.")
    print(f"Манифест: {MANIFEST.relative_to(PROJECT)}")
    if stale:
        print(f"В оверлее есть файлы, которых больше нет в дереве: {stale}")
    return 0


def load_manifest() -> dict:
    if not MANIFEST.exists():
        raise SystemExit(f"нет манифеста: {MANIFEST}")
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def apply(vendor: Path, dry_run: bool) -> int:
    manifest = load_manifest()
    print(f"Продукт поверх {manifest['upstream']['name']} "
          f"{manifest['upstream']['release']}: {vendor}")
    if not vendor.is_dir():
        raise SystemExit(f"нет дерева консоли: {vendor}")

    current = updated = added = 0
    foreign = []
    for entry in manifest["files"]:
        rel = Path(entry["path"])
        target = vendor / rel
        source = OVERLAY / rel
        if not source.exists():
            raise SystemExit(f"в оверлее нет файла {rel}, которого требует манифест")

        if target.exists():
            actual = sha256(target)
            if actual == entry["product_sha256"]:
                current += 1
                continue
            if entry["pristine_sha256"] and actual == entry["pristine_sha256"]:
                if not dry_run:
                    shutil.copyfile(source, target)
                updated += 1
                continue
            foreign.append((entry["path"], actual))
            continue

        if entry["kind"] == "new":
            if not dry_run:
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, target)
            added += 1
            continue
        foreign.append((entry["path"], "(файла нет)"))

    for path, actual in foreign:
        print(f"ОТКАЗ: {path} изменён не нами (sha256 {actual}). "
              f"Сверьте вручную, ничего не перезаписано.")
    verb = "будет сделано" if dry_run else "сделано"
    print(f"{verb}: уже актуальны {current}, обновлено {updated}, добавлено {added}, "
          f"отказано {len(foreign)}.")
    return 1 if foreign else 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    builder = sub.add_parser("build", help="записать текущее дерево консоли в репозиторий")
    builder.add_argument("--pristine", required=True, type=Path)
    builder.add_argument("--vendor", required=True, type=Path)

    applier = sub.add_parser("apply", help="наложить записанные файлы на дерево консоли")
    applier.add_argument("--vendor", required=True, type=Path)
    applier.add_argument("--dry-run", action="store_true")

    args = parser.parse_args(argv)
    if args.command == "build":
        return build(args.pristine, args.vendor)
    return apply(args.vendor, args.dry_run)


if __name__ == "__main__":
    raise SystemExit(main())
